name: MysticLanguageAPI
main: hu.mysticland.mysticlanguageapi.MysticLanguageAPI
version: 1.1.53
depend:
  - RedLib
  - KotlinCraft
api-version: 1.16
author: GeryyHUN23
description: Nyelvfordító API a MysticLand szerverre